### ISSUE TITLE
Endrex wont load "NoSuchFieldError: BLANK_RUNE"

### ISSUE THREAD

**Issue by PhantumOne** [nahkd123/Endrex#3]
Enabling Endrex v1.0.0
Could not save config.yml to plugins\Endrex\config.yml because config.yml already exists.
Error occurred while enabling Endrex v1.0.0 (Is it up to date?).
java.lang.NoSuchFieldError: BLANK_RUNE

Install all Slimefun4 current version plugins, addons including Endrex for PaperMC 1.15.2 buils 208.

Expected the plugin to load.

https://pastebin.com/m7r1RNEL

You are running the latest version!
Paper v1_15_R1

CS-CoreLib vDEV - 84 (git 0d29dbee)
Slimefun vDEV - 487 (git ca6170e6)

Installed Addons (19)
DyedBackpacks vDEV - 5 (git 129670c7)
SoundMuffler vDEV - 10 (git 545192ca)
SlimefunOreChunks vDEV - 8 (git 41e31ffc)
ExtraToolsPlugin vDEV - 9 (git 84269b5a)
SlimeXpansion vDEV - 15 (git 57438f88)
HotbarPets vDEV - 26 (git 7489ae00)
ExtraGear vDEV - 9 (git e851d81d)
SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
ExoticGarden vDEV - 39 (git 43a30365)
Barrels vDEV - 11 (git abecba9c)
ElectricSpawners vDEV - 10 (git 6c891f7f)
ExtraHeads vDEV - 14 (git 596a0822)
WhatIsThis v2.9
SoulJars vDEV - 15 (git dd58f105)
MobCapturer vDEV - 7 (git b61d3fbf)
SlimyTreeTaps vDEV - 10 (git 66d1dd72)
PrivateStorage vDEV - 11 (git b064863b)
ColoredEnderChests vDEV - 12 (git 8dbdc909)
ChestTerminal vDEV - 30 (git 04393688)

Plugins (85): AuctionHouse, AutomaticInventory, AutoPickup, Barrels, BeaconPlus2*, BeehivesPro, BetterShulkerBoxes, BKCommonLib, ChestTerminal, ClearLag, ColoredEnderChests, CommandSigns, CraftBook, CS-CoreLib, CustomCobbleGen, CustomEnderChest, DyedBackpacks, ElectricSpawners, EmeraldEnchants, EntityTrackerFixer, EpicFarming, EpicFurnaces, EpicHoppers, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExoticGarden, ExtraGear, ExtraHeads, ExtraToolsPlugin, FabledSkyBlock, GriefPrevention, GSit, GUIWarps, HolographicDisplays, HotbarPets, IronicChest, Jobs, JoinMessagePlus*, LightAPI*, LimitPillagers, LuckPerms, MeteoritesPro, MobCapturer, MorphMining, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MySkin, PickupArrows, PlaceholderAPI, PrivateStorage, ProtectionLib*, ProtocolLib, Realistic-Swimming, ShinyItems, ShopGUIPlus, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimeXpansion, SlimyTreeTaps, SoulJars, SoundMuffler, TabList, TCCoasters, Train_Carts, TridentCraft, UltimateFishing, UltimateKits, UltimateRepairing, UltimateStacker, UltimateTimber, Vault, VeinMiner, volcano, WhatIsThis, Wild, WorldEdit, WorldGuard, WorldSpawn*, XP-Deposit*

 - Minecraft Version: PaperMC 1.15.2 Build 208
 - CS-CoreLib Version: DEV - 84 (git 0d29dbee)
 - Slimefun Version: DEV - 487 (git ca6170e6)
 - Plugin Version: 1.0.0

**Comment by ghost** [comment]
I tried to load just CS_CoreLib, Slimefun, with Endrex, and this also happened
Just found that this only happen at the first time SF checking for update, no more :D

**Comment by nahkd123** [comment]
Have you tried Endrex v1.0.1 yet? I just recently released the new version, hopefully it will solve the problem.

This probably due to changes from the Slimefun plugin, where Endrex couldn't find "BLANK_RUNE" item.

**Comment by ghost** [comment]
Hehe, pro có khác
Now better than ever :D

**Comment by nahkd123** [comment]
Well, it's 7 days since you created this issue, and I get no response from you, so I decide to close this.
