### ISSUE TITLE
Endrex config already exists

### ISSUE THREAD

**Issue by bobhenl** [nahkd123/Endrex#9]
## Description (Required)
Hi, when you try to enable server with endrex installed and probably auto-update on in cscorelib, slimefun, etc., there is message in console (mentioned below)

## Steps to reproduce the Issue (Required)
Upload plugin and enable auto update in cscorelib and slimefun + enable server.

## Expected behavior (Required)
Won't appear this message.

## Server Log / Error Report
`[13:42:00 WARN]: [Endrex] Could not save config.yml to plugins/Endrex/config.yml because config.yml already exists.`

## Environment (Required)

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version: 88
 - Slimefun Version: 584
 - Plugin Version: 1.0.2-b1

**Comment by nahkd123** [comment]
This does not affect to your server. It just simply print the message that there's another config file exists in plugin data folder. The plugin will continue to load normally.
